### PR TITLE
Set Swift version to 2.3 for Xcode 8 compatibility

### LINKED ISSUE #174: iOS 10 requires Swift 3.0 code.
When I am running this code in Xcode 8.2 beta, It is throwing lot of errors. Most of them were deprecated. Can you please help to solve this.

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Fixes #174

### CODE REVIEW

**Comment by inceptiveDipak** [comment]
Hello @EddyVerbruggen, Thanks for your reply, Can u give me some steps for setting Swift version to 2.3 for Xcode 8 compatibility.
Thank you

**Comment by EddyVerbruggen** [comment]
Either of these:
* Wait for this PR to be merged
* Use the fork this PR came from
* Open Xcode 8, go to build settings and look the thing Google tells you to change when this error pops up

**Comment by inceptiveDipak** [comment]
Hey @EddyVerbruggen thanks for your reply, When it will be merged on master branch. 
Thank you.

**Comment by videmort** [comment]
Hello, I tried your solution but doesn't working with xCODE 8 and Cordova 6 +.

**Comment by tsubik** [comment]
@EddyVerbruggen looks like this only works when removing and adding this plugin. It doesn't work on clean project platform add command (at least for me). I'm planning to switch from my custom hook to https://github.com/akofman/cordova-plugin-add-swift-support. I have to test it first.

**Comment by videmort** [comment]
@tsubik @EddyVerbruggen Yes is working but only when you remove and add the plugin

**Comment by tsubik** [comment]
@videmort I've added the plugin I was talking about 68ca59c, so this PR is not needed anymore. The new approach works when reinstalling plugin as well as on clean platform add.

**Comment by videmort** [comment]
Great!

**Comment by Buddikazz** [comment]
when build with ios error: 'Geo-Bridging-Header.h' file not found
#import "Geo-Bridging-Header.h"

**Comment by tsubik** [comment]
@Buddikazz you have to reinstall plugin.

**Comment by Buddikazz** [comment]
yes i remove and reinstall the plugin still the same.

**Comment by tsubik** [comment]
You can try manually remove Briding-Header file from your xCode project (the one where is the line #import "Geo-Bridging-Header.h"). This file should be now created by additional plugin cordova-plugin-add-swift-support.

**Comment by Buddikazz** [comment]
Still i'm facing with the issue with manually deleting

**Pull request closed without merging**
