### PR TITLE
Working Copy for iOS 9 - Xcode 7 - Swift 2.0

### PR DESCRIPTION
**Pull request by Mojo90**
Does work for me on iOS 9 GM. Think should also work on iOS 9 final tomorrow on.
Fixes Issue #81

### CODE REVIEW

**Comment by tsubik** [comment]
Hey, I'm quite busy recently, what about backward compatibility? Is this backward compatible? Can I compile this on xcode 6.x and swift 1.2?

**Comment by Mojo90** [comment]
No Problem, me too. Just got an invitation for Web Summit ALPHA Class 2015, therefore I needed to fix that for my Project - a iOS 9 working copy.
To my knowledge: 
    - For iOS 9 you need Xcode 7.0 and Xcode 7.0 requires Swift 2.0
    - Swift 2.0 is not compilable with Xcode 6 --> Xcode 6 only supports Swift 1.2
    - I tested this build with iOS 8.4 on Xcode 7.0 and it worked for me --> some statements required at
      least iOS 8 such as "locationManager.requestAlwaysAuthorization()" in "class
      GeoNotificationManager" so I think it is not compatible with iOS 7 anymore.

**Comment by johnrobertcobbold** [comment]
Thanks @Mojo90, I installed your fork and it's now working for me, iOS9/Xcode7

**Comment by Mojo90** [comment]
@johnrobertcobbold  Great, thats good thanks!
If you experience an issue please contact me...

**Comment by andiCR** [comment]
Xcode 7 is breaking everything on my project (several plugins plus ionic itself). Was there any functionality changes on your commit @Mojo90 or was it purely a rewrite? I would like to provide a fix on xcode 6.4 to fix 1 issue, than handle about 30 more issues on the project.

**Comment by Mojo90** [comment]
Mh I have XCode 7.0.1 and works just fine for me... it can not work with Xcode 6.4 as I stated above. Was a bit tricky to figure this out but please check my comment above on this.... And I needed Swift 2.0 due to other Plugins. So I did no changes only Rewrite working copy for iOS 9 - Xcode 7 - Swift 2.0
What plugins are you using? I fixed everything to work with new XCode and in the meanwhile Plugin list is very long...

**Comment by tsubik** [comment]
Hey ok, I am going merge this into master and if no other problems appear I will release new plugin version within few days. Thanks @Mojo90 :+1:

**Comment by iori57** [comment]
Hi Mojo90, I've been using the swift 2.0 geofence plugin on your branch with success. However I found that when I compile the app on release mode the app will crash on startup (right after splash screen is shown). On debug mode it can run fine. 

Any idea on what could be the problem? Been trying to debug it for a while now.

Setting Optimization level to 'None' as suggested in forums doesn't solve the issue too.

Anyone else encounter this issue?

**Comment by shtaif** [comment]
@iori57 the problem you mention is about Android, not iOS, right?

**Comment by Mojo90** [comment]
@shtaif as we are in an iOS-only Pull Request I do think it is iOS related.
@iori57 Mh my App is even in the AppStore and runs. Not sure what the problem would be. I've Bitcode Disable as for Facebook Plugin and also Disabled the new Compression Mode from Apple because this caused my App to crash. Have to investigate further of this comes from Geofence Plugin or from somewhere else...

**Comment by derek1988ec** [comment]
@iori57 @Mojo90 I got this problem as well. The solution was very simple although it took a while to figure it out. You can check the link of the problem from apple
https://developer.apple.com/library/ios/qa/qa1886/_index.html
Basically there's a new attribute declared in order to invoke the library. So I re-created my certificate and provisioning profile and it works!

**Pull request merged**
